# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.IntegerField()),
                ('mil_country', models.TextField(blank=True, null=True)),
                ('mil_branch', models.TextField(blank=True, null=True)),
                ('mil_rank', models.TextField(blank=True, null=True)),
                ('mil_date', models.TextField(blank=True, null=True)),
                ('mil_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MilEntries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_type_id', models.IntegerField()),
                ('node_title', models.TextField()),
            ],
            options={
                'db_table': 'Nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nodetypes',
            fields=[
                ('node_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_type', models.TextField()),
            ],
            options={
                'db_table': 'NodeTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.IntegerField()),
                ('pat_title', models.TextField(blank=True, null=True)),
                ('pat_url', models.TextField(blank=True, null=True)),
                ('pat_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PatEntries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pubentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.IntegerField()),
                ('pub_title', models.TextField(blank=True, null=True)),
                ('pub_url', models.TextField(blank=True, null=True)),
                ('pub_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PubEntries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skillentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk_id', models.IntegerField()),
                ('usr_id', models.IntegerField()),
            ],
            options={
                'db_table': 'SkillEntries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skillnames',
            fields=[
                ('sk_id', models.AutoField(primary_key=True, serialize=False)),
                ('sk_name', models.TextField()),
            ],
            options={
                'db_table': 'SkillNames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trajectoryentries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.IntegerField()),
                ('node_id', models.IntegerField()),
                ('org_name', models.TextField(blank=True, null=True)),
                ('org_location', models.TextField(blank=True, null=True)),
                ('start_date_str', models.TextField(blank=True, null=True)),
                ('end_date_str', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date_month_int', models.IntegerField(blank=True, null=True)),
                ('start_date_year_int', models.IntegerField(blank=True, null=True)),
                ('start_date_year_month_int', models.IntegerField(blank=True, null=True)),
                ('end_date_month_int', models.IntegerField(blank=True, null=True)),
                ('end_date_year_int', models.IntegerField(blank=True, null=True)),
                ('end_date_year_month_int', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TrajectoryEntries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trajectorytemp',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_node_id', models.TextField()),
            ],
            options={
                'db_table': 'TrajectoryTemp',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='linkentries',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
